"""initial schemas and tables

Revision ID: efd062033d5a
Revises: 
Create Date: 2026-04-04 19:01:49.121931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efd062033d5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_table('disruption_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('neo4j_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('affected_zone_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='disruptions'
    )
    op.create_index(op.f('ix_disruptions_disruption_records_neo4j_id'), 'disruption_records', ['neo4j_id'], unique=True, schema='disruptions')
    op.create_table('equipment_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('neo4j_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('hs_code', sa.String(length=20), nullable=True),
    sa.Column('project_neo4j_id', sa.String(length=20), nullable=True),
    sa.Column('supplier_neo4j_id', sa.String(length=20), nullable=True),
    sa.Column('route_neo4j_id', sa.String(length=20), nullable=True),
    sa.Column('required_on_site_date', sa.Date(), nullable=True),
    sa.Column('value_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='equipment'
    )
    op.create_index(op.f('ix_equipment_equipment_registry_neo4j_id'), 'equipment_registry', ['neo4j_id'], unique=True, schema='equipment')
    op.create_index(op.f('ix_equipment_equipment_registry_project_neo4j_id'), 'equipment_registry', ['project_neo4j_id'], unique=False, schema='equipment')
    op.create_index(op.f('ix_equipment_equipment_registry_route_neo4j_id'), 'equipment_registry', ['route_neo4j_id'], unique=False, schema='equipment')
    op.create_index(op.f('ix_equipment_equipment_registry_supplier_neo4j_id'), 'equipment_registry', ['supplier_neo4j_id'], unique=False, schema='equipment')
    op.create_table('route_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('neo4j_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('origin_port', sa.String(length=100), nullable=True),
    sa.Column('destination_port', sa.String(length=100), nullable=True),
    sa.Column('distance_nm', sa.Float(), nullable=True),
    sa.Column('base_transit_days', sa.Integer(), nullable=True),
    sa.Column('base_shipping_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('base_insurance_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='routes'
    )
    op.create_index(op.f('ix_routes_route_records_neo4j_id'), 'route_records', ['neo4j_id'], unique=True, schema='routes')
    op.create_table('supplier_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('neo4j_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('financial_rating', sa.Float(), nullable=True),
    sa.Column('capacity_utilization', sa.Float(), nullable=True),
    sa.Column('is_sanctioned', sa.Boolean(), nullable=True),
    sa.Column('risk_flags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('certifications', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('capabilities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='suppliers'
    )
    op.create_index(op.f('ix_suppliers_supplier_profiles_neo4j_id'), 'supplier_profiles', ['neo4j_id'], unique=True, schema='suppliers')
    op.create_table('impact_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disruption_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('affected_equipment_count', sa.Integer(), nullable=True),
    sa.Column('affected_project_count', sa.Integer(), nullable=True),
    sa.Column('affected_route_count', sa.Integer(), nullable=True),
    sa.Column('total_cost_impact', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('estimated_delay_days', sa.Integer(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.disruption_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='disruptions'
    )
    op.create_index('ix_impact_disruption_ts', 'impact_snapshots', ['disruption_id', 'snapshot_at'], unique=False, schema='disruptions')
    op.create_table('delivery_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='equipment'
    )
    op.create_index('ix_delivery_equip_date', 'delivery_events', ['equipment_id', 'event_date'], unique=False, schema='equipment')
    op.create_table('route_cost_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('insurance_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fuel_surcharge', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('congestion_surcharge', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transit_days_actual', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='routes'
    )
    op.create_index('ix_route_cost_date', 'route_cost_history', ['route_id', 'recorded_date'], unique=False, schema='routes')
    op.create_table('supplier_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('on_time_delivery_rate', sa.Float(), nullable=True),
    sa.Column('quality_reject_rate', sa.Float(), nullable=True),
    sa.Column('average_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('orders_completed', sa.Integer(), nullable=True),
    sa.Column('total_value_delivered', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='suppliers'
    )
    op.create_index('ix_supplier_perf_period', 'supplier_performance', ['supplier_id', 'period_start'], unique=False, schema='suppliers')
    op.create_table('tco_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disruption_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('baseline_tco', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.disruption_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tco'
    )
    op.create_table('decision_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tco_report_id', sa.UUID(), nullable=True),
    sa.Column('decision_type', sa.String(length=50), nullable=True),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tco_report_id'], ['tco.tco_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_table('tco_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alternative_route_id', sa.String(length=20), nullable=True),
    sa.Column('alternative_supplier_id', sa.String(length=20), nullable=True),
    sa.Column('affected_equipment_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('implementation_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('shipping_cost_delta', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('insurance_cost_delta', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('lead_time_delta_days', sa.Integer(), nullable=True),
    sa.Column('delay_penalty_savings', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_tco', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tco_delta_vs_baseline', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('risk_reduction_pct', sa.Float(), nullable=True),
    sa.Column('net_savings', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('benefit_cost_ratio', sa.Float(), nullable=True),
    sa.Column('recommendation_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['tco.tco_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tco'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tco_scenarios', schema='tco')
    op.drop_table('decision_logs', schema='audit')
    op.drop_table('tco_reports', schema='tco')
    op.drop_index('ix_supplier_perf_period', table_name='supplier_performance', schema='suppliers')
    op.drop_table('supplier_performance', schema='suppliers')
    op.drop_index('ix_route_cost_date', table_name='route_cost_history', schema='routes')
    op.drop_table('route_cost_history', schema='routes')
    op.drop_index('ix_delivery_equip_date', table_name='delivery_events', schema='equipment')
    op.drop_table('delivery_events', schema='equipment')
    op.drop_index('ix_impact_disruption_ts', table_name='impact_snapshots', schema='disruptions')
    op.drop_table('impact_snapshots', schema='disruptions')
    op.drop_index(op.f('ix_suppliers_supplier_profiles_neo4j_id'), table_name='supplier_profiles', schema='suppliers')
    op.drop_table('supplier_profiles', schema='suppliers')
    op.drop_index(op.f('ix_routes_route_records_neo4j_id'), table_name='route_records', schema='routes')
    op.drop_table('route_records', schema='routes')
    op.drop_index(op.f('ix_equipment_equipment_registry_supplier_neo4j_id'), table_name='equipment_registry', schema='equipment')
    op.drop_index(op.f('ix_equipment_equipment_registry_route_neo4j_id'), table_name='equipment_registry', schema='equipment')
    op.drop_index(op.f('ix_equipment_equipment_registry_project_neo4j_id'), table_name='equipment_registry', schema='equipment')
    op.drop_index(op.f('ix_equipment_equipment_registry_neo4j_id'), table_name='equipment_registry', schema='equipment')
    op.drop_table('equipment_registry', schema='equipment')
    op.drop_index(op.f('ix_disruptions_disruption_records_neo4j_id'), table_name='disruption_records', schema='disruptions')
    op.drop_table('disruption_records', schema='disruptions')
    op.drop_table('change_logs', schema='audit')
    # ### end Alembic commands ###
